platform: x64

clone_depth: 1

environment:
  PYTHON: C:\Python37-x64

init:
- SET PATH=%PATH%;%PYTHON%;%PYTHON%\Scripts
- SET PYTHONIOENCODING=utf-8

install:
# pip upgading required, because otherwise AppVeyor failed, compare:
# https://ci.appveyor.com/project/Kristinita/erichek/build/1.0.34
# https://ci.appveyor.com/project/Kristinita/erichek/build/1.0.33
- "%PYTHON%\\python -m pip install --upgrade pip"
# Temporary hack for Gevent:
# https://github.com/getlogbook/logbook/issues/270
# https://github.com/gevent/gevent/issues/1260
- 'pip3 install -U --force-reinstall --no-binary :all: gevent'
# Needs “-U”, because pyroma works incorrect in old setuptools versions:
# https://github.com/regebro/pyroma/issues/16#issuecomment-362795949
# [BUG] Disable pylint_runner:
# https://ci.appveyor.com/project/Kristinita/erichek#L211
- pip3 install -U flake8 pydocstyle pyroma setuptools twine vulture wheel
- pip3 install -r requirements.txt

build_script:
- flake8 .
- pydocstyle
- pyroma -n 10 .
- vulture .
