environment:

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"

platform: x64

install:

  # Needs, because will get messages as:
  # «flake8 is not recognized»
  # https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
  # Python 2 by default, see:
  # https://www.appveyor.com/docs/build-environment/#python
  # https://ci.appveyor.com/project/Kristinita/erichek/build/1.0.3
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # pip upgading required, because otherwise AppVeyor failed, compare:
  # https://ci.appveyor.com/project/Kristinita/erichek/build/1.0.34
  # https://ci.appveyor.com/project/Kristinita/erichek/build/1.0.33
  - cmd: python -m pip install --upgrade pip
  - cmd: pip install flake8
  - cmd: pip install pydocstyle
  - cmd: pip install pyroma
  # Needs, because pyroma works incorrect in old setuptools versions:
  # https://github.com/regebro/pyroma/issues/16#issuecomment-362795949
  - cmd: pip install -U setuptools
  - cmd: pip install vulture

build_script:

  # Needs AppVeyor console set, see:
  # https://stackoverflow.com/a/48093971/5951529
  - cmd: set PYTHONIOENCODING=utf-8
  - cmd: flake8 .
  - cmd: pydocstyle
  - cmd: pyroma .
  - cmd: vulture .